/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b78982d5-232a-4417-bcea-e0b80ec0a040",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Eumi7c8aa",
    "aws_user_pools_web_client_id": "7p7sa0rukgn4fhvu59uis5e3pp",
    "oauth": {}
};


export default awsmobile;
